name: weather_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  lottie: ^3.1.0
  animated_splash_screen: ^1.3.0
  google_fonts: ^6.2.1
  dotted_line: ^3.2.2
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: 'assets/weatherapplogo.png'



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sunny.json
    - assets/cloudy.json
    - assets/thunder.json
    - assets/rainy.json
    - assets/suncloudy.json
    - assets/fog.json
    - assets/drizzle.json
    - assets/loading.json
    - assets/mainload.json
    - assets/nightcloudy.json
    - assets/nightrainy.json
    - assets/moonie.json
